## Numpy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these datastructures

In [7]:
import numpy as np

## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)

## The shape of this array is (5,). This is a single dimension array with 5 elements. Thats the reason it returned (5,). 
# Whenever there is a blank on second element, it means it is a single dimension array. Here we dont have any specific rows or columns. 
print(arr1.shape)

[1 2 3 4 5]
(5,)


In [19]:
## THIS IS NOT WORKING
## Reshaping the array to a two dimensional array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns
arr2

array([1, 2, 3, 4, 5])

In [ ]:
## Creating a two dimensional array
## We can create a two dimensional array by giving a nested list (list of lists) as an input to np.array
arr3 = np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [28]:
arr4 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr4


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [ ]:
#This creates a one dimensional array starting from 0 (inclusive) and ending with 10 (exclusive) and will have a step count of 2 (takes every 2nd element)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
## This function will create a two dimensional array with 3 rows and 4 columns and all elements are 1
## Remember it takes a set as an input. Check the double openeing and closing braces
## This function will help us create an initial array with all values initialized to 1. Saves us effort from populating the values manually
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
## identity matrix. In Identity matrix, number of rows and columns will be save. All the diagonal elements will be 1 and remaining will be zero. 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape: ", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes)", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes) 8


In [47]:
## NumPy Vectorized Operations
## For element wise operations to work, the number of elements in both the arrays should be the same
## For element wise operations to work, the datatype of elements to be added should be the same. 

arr1 = np.array([1,2,3,4,5,])
arr2 = np.array([6,7,8,9,1])

## Element wise addition
arr1+arr2

## Element wise subtraction 
arr1-arr2

## Element wise multiplication
arr1*arr2

## Element wise division
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 5.        ])

In [50]:
## Universal functions
## Functions that are applicable to all the elements of the array

arr = np.array([1,2,3,4,5])

## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
## array slicing and indexing

arr = np.array([[1,2,3,4,5],[5,6,7,8,9],[4,5,6,7,8]])

## Fetch row at an index
arr[1]

## Fetch a particular field in a row
arr[1][1]

## Fetch all the rows starting from the second row
arr[1:]

## Fetch all the records from 1st row from 2nd index
arr[1,1:]

## Slice a square of the last 4 elements
arr[1:,3:]

## From the second row, slice the mid three elements. Here, the upper boundi s not inclusive
arr[1,1:4]


array([6, 7, 8])

In [75]:
## Modify array elements
arr[0,0]=100

## Modify all the elements from 1st row to 1000
arr[1:]=1000

arr

array([[ 100,    2,    3,    4,    5],
       [1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000]])

In [76]:
## Statistical concepts - Normalization
## To have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [80]:
## Statistical concepts - mean, median, standard deviation, variance

data = np.array([1,2,3,4,5])

mean = np.mean(data)
print("Mean: ", mean)

median = np.median(data)
print("Median: ", median)

std_dev = np.std(data)
print("Standard Deviation:", std_dev)

variance = np.var(data)
print("Variance:", variance)

Mean:  3.0
Median:  3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [83]:
## Logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data > 5

## Retrieve all the elements that have a value greater than 5
data[data>5]

## Retrieve all the elements that are greater than 5 and lesser than 8
data[(data>5) & (data<8)]

array([6, 7])